export const faServicesContent = {
  eyebrow: "خدمات",
  title: "نمونه کار های ما",
  title2: "ایده ها به واقعیت تبدیل میشوند",
  intro: "در این بخش،بخشی از پروژه های موفق و همکارهای ما را مشاهده میکنید.",
  offerings: [
    {
      title: "طراحی فروشگاه آنلاین",
      summary: "فروشگاه سازه و پنل های خورشیدی",
      tech: ["React", "TypeScript", "Mui"],
      link: "https://ecosaze.com",
      tags: "websit",
      tags_persian: "وب سایت",
    },
    {
      title: "طراحی مغازه آنلاین",
      summary: "فروشگاه سازه و پنل های خورشیدی",
      tech: ["React", "TypeScript", "React Query"],
      link: "https://ecosaze.com",
      tags: "websit",
      tags_persian: "وب سایت",
    },
    {
      title: " فروشگاه آنلاین",
      summary: "فروشگاه سازه و پنل های خورشیدی",
      tech: ["Nextjs", "TypeScript", "Mui"],
      link: "https://ecosaze.com",
      tags: "ecommers",
      tags_persian: "فروشگاه",
    },
    {
      title: "اپلیکشین فروشگاه آنلاین",
      summary: "فروشگاه سازه و پنل های خورشیدی",
      tech: ["React Native", "TypeScript", "Mui"],
      link: "https://ecosaze.com",
      tags: "app",
      tags_persian: "اپلیکیشن",
    },
    {
      title: "اپلیکشین مغازه آنلاین",
      summary: "فروشگاه سازه و پنل های خورشیدی",
      tech: ["React", "TypeScript", "Mui"],
      link: "https://ecosaze.com",
      tags: "app",
      tags_persian: "اپلیکیشن",
    },
  ],
} as const;
